name: release

on:
  push:
    tags:
      - "v*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    name: build and publish nuget package
    steps:
      - uses: actions/checkout@master
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: "latest"
          
      - uses: nowsprinting/check-version-format-action@v3.2.3
        id: version
        with:
          prefix: 'v'
          
      - run: nuget pack sensslen.styles.nuspec -Version ${{ steps.version.outputs.full_without_prefix }}
      
      - name: Upload Package
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_ORG_API_KEY}}

